-- Script SQL revisado com INSERTs
-- MySQL Script generated by MySQL Workbench
-- Model: Patinhas do Bem

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_PatinhasDoBem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_patinhasdobem` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_patinhasdobem` ;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Bairro` VARCHAR(145) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  `Email` VARCHAR(300) NOT NULL,
  `Senha` VARCHAR(300) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `Administrador` TINYINT NOT NULL DEFAULT '0'
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postagem` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Descricao` VARCHAR(500) NOT NULL,
  `dataPublicacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDUsuario` INT NOT NULL,
  FOREIGN KEY (`IDUsuario`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `IDPostagem` INT NOT NULL,
  `IDUsuario` INT NOT NULL,
  FOREIGN KEY (`IDPostagem`) REFERENCES `postagem`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDUsuario`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comentario` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Texto` VARCHAR(500) NOT NULL,
  `Data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDPostagem` INT NOT NULL,
  `IDUsuario` INT NOT NULL,
  FOREIGN KEY (`IDPostagem`) REFERENCES `postagem`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDUsuario`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `dataRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TipoAnimal` VARCHAR(45) NOT NULL,
  `Linhagem` VARCHAR(45) NOT NULL,
  `Status` TINYINT NOT NULL,
  `Idade` VARCHAR(3) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(500) NULL DEFAULT NULL,
  `IDDoador` INT NOT NULL,
  FOREIGN KEY (`IDDoador`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contato` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Interessado` TINYINT NOT NULL,
  `Data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDSolicitante` INT NOT NULL,
  `IDPetInteressado` INT NOT NULL,
  `IDDestinatario` INT NOT NULL,
  FOREIGN KEY (`IDSolicitante`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDPetInteressado`) REFERENCES `pet`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denuncia` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Causa` VARCHAR(300) NOT NULL,
  `IDUsuario` INT NOT NULL,
  `IDPostagem` INT NOT NULL,
  FOREIGN KEY (`IDUsuario`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDPostagem`) REFERENCES `postagem`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interesse` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Status` TINYINT NOT NULL,
  `IDInteressado` INT NOT NULL,
  `IDPet` INT NOT NULL,
  FOREIGN KEY (`IDInteressado`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDPet`) REFERENCES `pet`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensagem` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `DataDeEnvio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IDRemetente` INT NOT NULL,
  `IDContato` INT NOT NULL,
  FOREIGN KEY (`IDRemetente`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDContato`) REFERENCES `contato`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `usuariosbloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosbloqueados` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `IDUsuario` INT NOT NULL,
  `IDUsuarioBloqueado` INT NOT NULL,
  FOREIGN KEY (`IDUsuario`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`IDUsuarioBloqueado`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificacao` (
  `ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `IDUsuario` INT NOT NULL,
  `Conteudo` VARCHAR(500) NOT NULL,
  `DataEnvio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`IDUsuario`) REFERENCES `usuario`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB ;


-- Inserir dados na tabela `usuario`
INSERT INTO `usuario` (`Nome`, `CEP`, `Rua`, `Numero`, `Bairro`, `Estado`, `DataNasc`, `Email`, `Senha`, `Pais`, `Administrador`) 
VALUES 
('Maria Silva', '12345-678', 'Rua A', 123, 'Bairro A', 'SP', '1990-05-15', 'maria@example.com', 'senha123', 'Brasil', 0),
('João Souza', '98765-432', 'Rua B', 456, 'Bairro B', 'RJ', '1985-07-20', 'joao@example.com', 'senha456', 'Brasil', 1);

-- Inserir dados na tabela `postagem`
INSERT INTO `postagem` (`Descricao`, `IDUsuario`) 
VALUES 
('Primeira postagem sobre adoção de animais', 1),
('Postagem sobre cuidados com pets', 2);

-- Inserir dados na tabela `avaliacao`
INSERT INTO `avaliacao` (`tipo`, `IDPostagem`, `IDUsuario`) 
VALUES 
('positivo', 1, 2),
('negativo', 2, 1);

-- Inserir dados na tabela `comentario`
INSERT INTO `comentario` (`Texto`, `IDPostagem`, `IDUsuario`) 
VALUES 
('Ótima postagem, parabéns!', 1, 2),
('Gostei muito das dicas!', 2, 1);

-- Inserir dados na tabela `pet`
INSERT INTO `pet` (`TipoAnimal`, `Linhagem`, `Status`, `Idade`, `Sexo`, `Cor`, `Descricao`, `IDDoador`) 
VALUES 
('Cão', 'SRD', 1, '2', 'M', 'Preto', 'Cachorro muito dócil', 1),
('Gato', 'Persa', 1, '3', 'F', 'Branco', 'Gata brincalhona', 2);

-- Inserir dados na tabela `contato`
INSERT INTO `contato` (`Interessado`, `IDSolicitante`, `IDPetInteressado`, `IDDestinatario`) 
VALUES 
(1, 1, 1, 2),
(1, 2, 2, 1);

-- Inserir dados na tabela `denuncia`
INSERT INTO `denuncia` (`Causa`, `IDUsuario`, `IDPostagem`) 
VALUES 
('Conteúdo inadequado', 1, 2),
('Spam', 2, 1);

-- Inserir dados na tabela `interesse`
INSERT INTO `interesse` (`Status`, `IDInteressado`, `IDPet`) 
VALUES 
(1, 1, 1),
(1, 2, 2);

-- Inserir dados na tabela `mensagem`
INSERT INTO `mensagem` (`IDRemetente`, `IDContato`) 
VALUES 
(1, 1),
(2, 2);

-- Inserir dados na tabela `usuariosbloqueados`
INSERT INTO `usuariosbloqueados` (`IDUsuario`, `IDUsuarioBloqueado`) 
VALUES 
(1, 2),
(2, 1);


-- Inserir dados na tabela `notificacao`
INSERT INTO `notificacao` (`IDUsuario`, `Conteudo`) 
VALUES 
(1, 'Você tem uma nova mensagem!'),
(2, 'Seu pet foi adotado!');

-- -----------------------------------------------------
-- Finalizações
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
