-- MySQL Script generated by MySQL Workbench
-- Corrections made
-- Model: DB_PatinhasDoBem    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_PatinhasDoBem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_PatinhasDoBem` DEFAULT CHARACTER SET utf8;
USE `DB_PatinhasDoBem`;

-- Tabela Avaliacao
CREATE TABLE avaliacao (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    tipo VARCHAR(20),
    IDPostagem INT,
    IDUsuario INT,
    FOREIGN KEY (IDPostagem) REFERENCES postagem(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDUsuario) REFERENCES usuario(ID) ON DELETE CASCADE
);

-- Tabela Comentario
CREATE TABLE comentario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Texto VARCHAR(500),
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IDPostagem INT,
    IDUsuario INT,
    FOREIGN KEY (IDPostagem) REFERENCES postagem(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDUsuario) REFERENCES usuario(ID) ON DELETE CASCADE
);

-- Tabela Contato
CREATE TABLE contato (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Interessado TINYINT,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IDSolicitante INT,
    IDPetInteressado INT,
    IDDestinatario INT,
    FOREIGN KEY (IDSolicitante) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDPetInteressado) REFERENCES pet(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDDestinatario) REFERENCES usuario(ID) ON DELETE CASCADE
);

-- Tabela Denuncia
CREATE TABLE denuncia (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Causa VARCHAR(300),
    IDUsuario INT,
    IDPostagem INT,
    FOREIGN KEY (IDUsuario) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDPostagem) REFERENCES postagem(ID) ON DELETE CASCADE
);

-- Tabela Interesse
CREATE TABLE interesse (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Status TINYINT,
    IDInteressado INT,
    IDPet INT,
    FOREIGN KEY (IDInteressado) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDPet) REFERENCES pet(ID) ON DELETE CASCADE
);

-- Tabela Mensagem
CREATE TABLE mensagem (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DataDeEnvio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IDRemetente INT,
    IDContato INT,
    FOREIGN KEY (IDRemetente) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDContato) REFERENCES contato(ID) ON DELETE CASCADE
);

-- Tabela Notificacao
CREATE TABLE notificacao (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Texto VARCHAR(100),
    IDDestinatario INT,
    IDComentario INT,
    IDPostagem INT,
    Recebimento TINYINT,
    FOREIGN KEY (IDDestinatario) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDComentario) REFERENCES comentario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDPostagem) REFERENCES postagem(ID) ON DELETE CASCADE
);

-- Tabela Pet
CREATE TABLE pet (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    dataRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TipoAnimal VARCHAR(45),
    Linhagem VARCHAR(45),
    Status TINYINT,
    Idade VARCHAR(3),
    Sexo VARCHAR(1),
    Cor VARCHAR(45),
    Descricao VARCHAR(500),
    IDDoador INT,
    FOREIGN KEY (IDDoador) REFERENCES usuario(ID) ON DELETE CASCADE
);

-- Tabela Postagem
CREATE TABLE postagem (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Descricao VARCHAR(500),
    dataPublicacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IDUsuario INT,
    FOREIGN KEY (IDUsuario) REFERENCES usuario(ID) ON DELETE CASCADE
);

-- Tabela SolicitacaoContato
CREATE TABLE solicitacaocontato (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDSolicitante INT,
    IDPetInteressado INT,
    IDDestinatario INT,
    FOREIGN KEY (IDSolicitante) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDPetInteressado) REFERENCES pet(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDDestinatario) REFERENCES usuario(ID) ON DELETE CASCADE
);

-- Tabela Usuario
CREATE TABLE usuario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(200),
    CEP VARCHAR(45),
    Rua VARCHAR(45),
    Numero INT,
    Bairro VARCHAR(145),
    Estado VARCHAR(45),
    DataNasc DATE,
    Email VARCHAR(300),
    Senha VARCHAR(300),
    Pais VARCHAR(45),
    Administrador TINYINT
);

-- Tabela UsuariosBloqueados
CREATE TABLE usuariosbloqueados (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    dataBloqueio DATE,
    IDBloqueado INT,
    IDBloqueador INT,
    FOREIGN KEY (IDBloqueado) REFERENCES usuario(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDBloqueador) REFERENCES usuario(ID) ON DELETE CASCADE
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `Usuario` (`Nome`, `CEP`, `Rua`, `Numero`, `Bairro`, `Estado`, `DataNasc`, `Email`, `Senha`, `Pais`, `Administrador`) 
VALUES 
('João Silva', '12345-678', 'Rua A', 123, 'Centro', 'SP', '1990-05-15', 'joao.silva@gmail.com', 'senha123', 'Brasil', 0),
('Maria Souza', '87654-321', 'Rua B', 456, 'Jardim', 'RJ', '1985-08-20', 'maria.souza@gmail.com', 'senha456', 'Brasil', 0),
('Carlos Pereira', '45678-123', 'Rua C', 789, 'Norte', 'MG', '1992-11-30', 'carlos.pereira@gmail.com', 'senha789', 'Brasil', 0),
('Ana Oliveira', '98765-432', 'Rua D', 101, 'Sul', 'SP', '1988-02-17', 'ana.oliveira@gmail.com', 'senha101', 'Brasil', 1);


INSERT INTO `Postagem` (`Descricao`, `dataPublicacao`)
VALUES ('Postagem sobre adoção de cães', NOW()),
       ('Postagem sobre resgate de gatos', NOW()),
       ('Evento de conscientização sobre adoção', NOW());
       
INSERT INTO `Avaliacao` (`tipo`, `IDPostagem`, `IDUsuario`)
VALUES ('like', 1, 1),
       ('dislike', 2, 2),
       ('like', 3, 3);

INSERT INTO `Comentario` (`Texto`, `Data`, `IDPostagem`, `IDUsuario`)
VALUES ('Excelente postagem!', NOW(), 1, 1),
       ('Concordo com tudo que foi dito', NOW(), 2, 2),
       ('Muito importante essa discussão', NOW(), 3, 3);

INSERT INTO `Denuncia` (`Causa`, `IDUsuario`, `IDPostagem`)
VALUES ('Conteúdo inadequado', 1, 1),
       ('Spam', 2, 2),
       ('Informações falsas', 3, 3);

INSERT INTO `UsuariosBloqueados` (`dataBloqueio`, `IDBloqueado`, `IDBloqueador`)
VALUES (CURDATE(), 2, 1),
       (CURDATE(), 3, 2);

INSERT INTO `Notificacao` (`Texto`, `IDDestinatario`, `IDComentario`, `IDPostagem`)
VALUES ('Você recebeu um novo comentário', 1, 1, 1),
       ('Sua postagem recebeu uma nova avaliação', 2, NULL, 2),
       ('Você foi mencionado em um comentário', 3, 3, NULL);

INSERT INTO `Pet` (`dataRegistro`, `TipoAnimal`, `Linhagem`, `Status`, `Idade`, `Sexo`, `Cor`, `IDDoador`)
VALUES (NOW(), 'Cachorro', 'SRD', 0, '3', 'M', 'Preto', 1),
       (NOW(), 'Gato', 'Angorá', 1, '2', 'F', 'Branco', 2),
       (NOW(), 'Cachorro', 'Pitbull', 0, '1', 'M', 'Marrom', 3);

INSERT INTO `Interesse` (`Status`, `IDInteressado`, `IDPet`)
VALUES (1, 1, 1),
       (0, 2, 2),
       (1, 3, 3);

INSERT INTO `SolicitacaoContato` (`IDSolicitante`, `IDPetInteressado`, `IDDestinatario`)
VALUES (1, 1, 2),
       (2, 2, 3),
       (3, 3, 1);

INSERT INTO `Contato` (`Interessado`, `Data`, `IDSolicitante`, `IDPetInteressado`, `IDDestinatario`)
VALUES (1, NOW(), 1, 1, 2),
       (0, NOW(), 2, 2, 3),
       (1, NOW(), 3, 3, 1);

INSERT INTO `Mensagem` (`DataDeEnvio`, `IDRemetente`, `IDContato`)
VALUES (NOW(), 1, 1),
       (NOW(), 2, 2),
       (NOW(), 3, 3);

