POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Gabriel",
  "password": "dankicode"
}


###

GET http://localhost:5000/users

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "name": "Gabriel",
  "password": "dankicode"
}


###

POST http://localhost:5000/Cadastro
Content-Type: application/json
{
  "Nome": "Gabriel",
  "DataNasc": "03/07/2003",
  "Email": "lucasmanrick.ipms@gmail.com",
  "Senha": "lucasteste321123",
  "Cep": "13178300",
  "Rua": "maria aparecida nascimento",
  "Numero": "252",
  "Bairro": "sumaré",
  "Estado": "sp",
}

 