POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Gabriel",
  "password": "dankicode"
}


###

GET http://localhost:5000/users

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "name": "Gabriel",
  "password": "dankicode"
}


###

POST http://localhost:5000/Cadastro
Content-Type: application/json

{
	"NomeUsuario":"Lucas Manrick",
	"DataNasc":"2003-07-03",
	"Email":"manrick@gmail.com",
	"Senha":"testelucas123",
	"Cep":"13178300",
	"Rua":"maria aparecida nascimento",
	"Numero":252,
	"Bairro":"Cidade Nova",
	"Estado": "SP",
	"Cidade": "Sumaré"
}

 